### ISSUE TITLE
Parabéns pelo projeto!

### ISSUE THREAD

**Issue by filipedeschamps** [higorpo/tabnews-mobile#1]
Acabei de acessar o repositório pelo link que você colocou no TabNews e fiquei MUITO feliz em ver essa iniciativa 🎉🤝

Parabéns meu caro!

**Comment by higorpo** [comment]
Fico feliz que tenha gostado @filipedeschamps :smile: 
Aproveitando que está aqui, existe alguma documentação para a API? Onde posso encontrá-la?

**Comment by xPryds** [comment]
Parabéns pelo projeto.
Quero ajudar a construir o cliente.  Acho que podemos aprender muito juntos.
@filipedeschamps consegue uma doc pra gente pensar em integrar com login, registro e postagem?

**Comment by filipedeschamps** [comment]
Ainda não tem documentação, mas se vocês lerem o código é bem fácil. Caso não tenham acesso ao repositório do tabnews, veja esse post: https://www.tabnews.com.br/filipedeschamps/quem-deseja-acesso-ao-repositorio-privado-do-tabnews

Mas em resumo, a API nesse caso é muito simples (vamos ver se eu lembro de cabeça):

### Criar conta
`POST` contra `/api/v1/users` para criar uma conta passando `username`, `email` e `password`.

### Login
`POST` contra `/api/v1/sessions` para fazer o login passando `email` e `password`.

Isso irá devolver um Cookie chamado `session_id` e que deve ser passado nas requests seguintes.

**Comment by xPryds** [comment]
Acabei de pegar o acesso ao repositório.
Vi aqui e está bem organizado. Vai ficar fácil pra replicar as features. 
Vamo nessa, vou pegar o tempo livre e tentar contribuir contigo @higorpo

**Comment by higorpo** [comment]
Muito bom @xPryds vamos nessa :) 
Vou tentar organizar essa semana o que precisa ser feito!

**Comment by filipedeschamps** [comment]
Agora que percebi que na parte de Login eu copiei uma parte do texto de criar conta 😂 ajustei mas acho que tinha dado para entender.

Em paralelo, uma sugestão é vocês testarem como quiser o ambiente de Homologação, inclusive desenvolver o App contra ele. Vocês vão poder criar novas contas (quantas quiserem para testar), criar posts, editar, e daí fica mais fácil usar isso para analizar a aba **Network** no navegador e repassar o que o client web está fazendo para o client app.

A URL com a última versão do site em homologação é essa: https://tabnews-6g5imv1cy-tabnews.vercel.app/

Vou fechar essa issue e parabéns de novo pelo projeto 🤝
